name = "kaipepler"
main = ".svelte-kit/cloudflare/_worker.js"
compatibility_date = "2025-09-13"
compatibility_flags = ["nodejs_compat"]
[assets]
directory = ".svelte-kit/cloudflare"
binding = "ASSETS"